name: CI
on: 
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      actions: "read"

    steps:
      - name: Change Directory
        run: cd ./high-performance_large-scale_frontend/08-fastcampus-front-project

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Derive Appropriate SHAs for vase and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Test
        run: yarn affected:test --parallel=5

      - name: Build
        run: yarn affected:build --parallel=5
